services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./db:/app/db
      - ./.env:/app/.env
    environment:
      - PORT=3000
    restart: always

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        VITE_POSTHOG_KEY: ${VITE_POSTHOG_KEY}
        VITE_POSTHOG_HOST: ${VITE_POSTHOG_HOST}
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
